### ISSUE TITLE
Disable based on filetype

### ISSUE THREAD

**Issue by avesst** [lukoshkin/trailing-whitespace#5]
Hi,

Is it possible to have this plugin not highlight whitespace depending on filetype?

**Comment by lukoshkin** [comment]
Hi @maetthew, sorry for the late reply
It is currently possible by providing an empty table next to a filetype you want to disable. For example,

```lua
    opts = {
      tws = "\\s\\+$",
      clear_on_bufleave = false,
      filetype_blacklist = {},
      palette = {
        markdown = {},
        other = {
          tws = "PaleVioletRed",
          ["\\S\\@<=\\s,\\@="] = "coral1",
          ["\\S\\@<=\\(#\\|--\\)\\@<! \\{2,3\\}\\S\\@=\\(#\\|--\\)\\@!"] = "LightGoldenrod3",
          ["\\(#\\|--\\)\\@<= \\{2,\\}\\S\\@="] = "#3B3B3B",
          ["\\S\\@<= \\{3,\\}\\(#\\|--\\)\\@="] = "#3B3B3B",
          ["\\t\\+"] = "plum4",
        },
      },
    },
```
↑ That's the default setup, but the markdown pattern is turned off.
↓ And to disable fallback highlighting for all unspecified patterns:
```lua
    opts = {
      tws = "\\s\\+$",
      clear_on_bufleave = false,
      filetype_blacklist = {},
      palette = {
        markdown = "<... your pattern ...>",
        python = "<... your pattern ...>",
        <... other pattern mappings ...>,
        other = {},
      },
    },
```
(NOTE here: **other = {}**)
It is not quite elegant in the code, but it works. So, just specify empty tables for types you want to blacklist

**Comment by avesst** [comment]
@lukoshkin Not sure what you mean about late reply, it's not even been 12 hours :)

Thanks for that solution. It seems to work (I changed `config` to `opts`), however, every time I start Neovim I get the message "Something strange about your config!" which seems to stem from [here](https://github.com/lukoshkin/highlight-whitespace/blob/197e2e6262527d8cd8b4115c19dc236bbdfd4f82/lua/highlight-whitespace/utils.lua#L61). I can't seem to find that anything isn't working, so not sure why that is displayed.

**Comment by lukoshkin** [comment]
I thought it had been 2 days already) Never mind
Yep, `config` is deprecated in this context, `opts` is a proper way to configure.
About the warning. It lets you know there is an unused key in your config. Likely you did a typo specifying an option. And thus, the default settings are used instead. If you still don't get which option is spelled incorrectly, send your config here
@maetthew

**Comment by avesst** [comment]
@lukoshkin It was the empty `filetype_blacklist`, removing that removes the warning.

What does `filetype_blacklist` even do? From the name and from [this code](https://github.com/lukoshkin/highlight-whitespace/blob/197e2e6262527d8cd8b4115c19dc236bbdfd4f82/lua/highlight-whitespace/core.lua#L54-L68) it looks like it should disable based on filetype?

Thanks a lot for your help and for making this plugin :)

**Comment by lukoshkin** [comment]
Yep, it should, but I've never actually used it. And it is implementation is a bit dull. I will remove it in the next patch. But the approach with passing empty tables will remain and get more robust after I tweak it
